// <auto-generated />
using System;
using CadenceAccounting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadenceAccounting.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251025030728_AddReportDesignerTables")]
    partial class AddReportDesignerTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadenceAccounting.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TableName", "RecordId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abfef2c0-8504-4dce-bc62-f4d074605271"),
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(915),
                            Email = "info@cadence-consulting.com",
                            Name = "Cadence Consulting LLC",
                            Phone = "(312) 555-0123",
                            TaxId = "12-3456789",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(917)
                        });
                });

            modelBuilder.Entity("CadenceAccounting.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInvoiced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiptFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("ReceiptImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("CadenceAccounting.Models.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("BankTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("ClientAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ContractDocument")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContractText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectNumber");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ProjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommonExpenses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("DefaultBudget")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("DefaultHourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DefaultTaxType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("ProjectTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("924da034-99fa-4c65-ba46-42f7413d2bbd"),
                            CommonExpenses = "[\"Travel\", \"Meals\", \"Supplies\", \"Equipment\", \"Software\"]",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1166),
                            DefaultBudget = 50000.00m,
                            DefaultHourlyRate = 75.00m,
                            DefaultTaxType = "1099",
                            Description = "Template for state government contracts",
                            Name = "State Contract",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1167)
                        });
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataBinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("ZIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComponentType");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportComponents");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("SourceName");

                    b.ToTable("ReportDataSources");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedUserGroups")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("bit");

                    b.Property<string>("PrintDateUDF")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReportGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsActive");

                    b.HasIndex("ReportGroup");

                    b.HasIndex("Title");

                    b.ToTable("ReportDefinitions");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExecutedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExecutionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ExecutionTimeMs")
                        .HasColumnType("int");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedBy");

                    b.HasIndex("ExecutionDate");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportExecutions");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FormatString")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsGroupBy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSortBy")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReportDataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SortDirection")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldName");

                    b.HasIndex("ReportDataSourceId");

                    b.ToTable("ReportFields");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilterValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FieldName");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportFilters");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("FromDataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JoinType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToDataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FromDataSourceId");

                    b.HasIndex("ReportId");

                    b.HasIndex("ToDataSourceId");

                    b.ToTable("ReportRelationships");
                });

            modelBuilder.Entity("CadenceAccounting.Models.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16778cd9-c797-43de-b851-eedef3224f88"),
                            Category = "Invoice",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(984),
                            Description = "Invoice number format template",
                            Key = "InvoiceNumberFormat",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(985),
                            Value = "INV-{ProjectNumber}-{Year}-{SequentialNumber}"
                        },
                        new
                        {
                            Id = new Guid("ea3cfc4d-72eb-4a4f-84af-888ad61376bb"),
                            Category = "Tax",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(992),
                            Description = "Default tax type for new projects",
                            Key = "DefaultTaxType",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(992),
                            Value = "1099"
                        },
                        new
                        {
                            Id = new Guid("2a5c36b0-52cf-4eca-bca5-cecea2e21deb"),
                            Category = "Tax",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1010),
                            Description = "Federal income tax withholding rate",
                            Key = "FederalWithholdingRate",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1011),
                            Value = "15.0"
                        },
                        new
                        {
                            Id = new Guid("283d7f47-c1ce-4e90-951d-b3f27708d682"),
                            Category = "Tax",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1013),
                            Description = "Illinois state tax rate",
                            Key = "IllinoisStateTaxRate",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1013),
                            Value = "4.95"
                        },
                        new
                        {
                            Id = new Guid("3c15929b-049a-4c6f-b36c-3450346f5f17"),
                            Category = "Tax",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1016),
                            Description = "Social Security tax rate",
                            Key = "SocialSecurityRate",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1016),
                            Value = "6.2"
                        },
                        new
                        {
                            Id = new Guid("33ccc79d-a314-4032-a519-b0d042e2bc0e"),
                            Category = "Tax",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1018),
                            Description = "Medicare tax rate",
                            Key = "MedicareRate",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1019),
                            Value = "1.45"
                        },
                        new
                        {
                            Id = new Guid("13fa99fa-007b-47d5-b07f-2310d61931f4"),
                            Category = "Project",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1023),
                            Description = "Default hourly rate for projects",
                            Key = "DefaultHourlyRate",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1023),
                            Value = "75.00"
                        },
                        new
                        {
                            Id = new Guid("d08bab15-a5dc-45f5-a094-c185be439fb4"),
                            Category = "Company",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1026),
                            Description = "Company name for invoices",
                            Key = "CompanyName",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1027),
                            Value = "Cadence Consulting LLC"
                        },
                        new
                        {
                            Id = new Guid("e79659b8-f254-40e3-bde4-e92ca19bc6de"),
                            Category = "Company",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1029),
                            Description = "Company email for invoices",
                            Key = "CompanyEmail",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1029),
                            Value = "info@cadence-consulting.com"
                        },
                        new
                        {
                            Id = new Guid("5e7912e2-61c8-4bf5-9a07-99adfe5e3299"),
                            Category = "Email",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1031),
                            Description = "SMTP server for email",
                            Key = "SMTP_Server",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1032),
                            Value = "smtp.office365.com"
                        },
                        new
                        {
                            Id = new Guid("f5eab7e1-4b63-4820-b11c-8fd4f9c99d5e"),
                            Category = "Email",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1036),
                            Description = "SMTP port for email",
                            Key = "SMTP_Port",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1036),
                            Value = "587"
                        },
                        new
                        {
                            Id = new Guid("c977bea5-077d-4a90-9346-3b93fb82e24c"),
                            Category = "Backup",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1038),
                            Description = "Backup frequency",
                            Key = "Backup_Frequency",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1047),
                            Value = "Daily"
                        },
                        new
                        {
                            Id = new Guid("9c986ff3-d827-4658-be33-6a609cac4600"),
                            Category = "Backup",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1049),
                            Description = "Backup location",
                            Key = "Backup_Location",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1049),
                            Value = "C:\\Backups\\CadenceAccounting"
                        },
                        new
                        {
                            Id = new Guid("f80a9c41-b4cd-48fc-b11c-f58b9372c019"),
                            Category = "UI",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1051),
                            Description = "Default theme",
                            Key = "Theme",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1052),
                            Value = "Journal"
                        },
                        new
                        {
                            Id = new Guid("9d8020ad-5751-4a36-ad21-31ad4047ebc9"),
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1066),
                            Description = "Session timeout in minutes",
                            Key = "SessionTimeout",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 691, DateTimeKind.Utc).AddTicks(1066),
                            Value = "30"
                        });
                });

            modelBuilder.Entity("CadenceAccounting.Models.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInvoiced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("CadenceAccounting.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd62b8cc-3f57-40f7-aec6-a217a9c6580c"),
                            CreatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 690, DateTimeKind.Utc).AddTicks(9863),
                            Email = "admin@cadence-consulting.com",
                            EmailVerified = true,
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$uwZDP5h.aUXWR//WUSC5FekyhJ5vJx9dwcwp8M/P8H21sw1HnbFga",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 10, 25, 3, 7, 25, 690, DateTimeKind.Utc).AddTicks(9875),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CadenceAccounting.Models.AuditLog", b =>
                {
                    b.HasOne("CadenceAccounting.Models.User", "ChangedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Expense", b =>
                {
                    b.HasOne("CadenceAccounting.Models.Project", "Project")
                        .WithMany("Expenses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Invoice", b =>
                {
                    b.HasOne("CadenceAccounting.Models.User", "CreatedByUser")
                        .WithMany("Invoices")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.Project", "Project")
                        .WithMany("Invoices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CadenceAccounting.Models.InvoiceItem", b =>
                {
                    b.HasOne("CadenceAccounting.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Payment", b =>
                {
                    b.HasOne("CadenceAccounting.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Project", b =>
                {
                    b.HasOne("CadenceAccounting.Models.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.User", "CreatedByUser")
                        .WithMany("Projects")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportComponent", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany("Components")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDataSource", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany("DataSources")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDefinition", b =>
                {
                    b.HasOne("CadenceAccounting.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportExecution", b =>
                {
                    b.HasOne("CadenceAccounting.Models.User", "ExecutedByUser")
                        .WithMany()
                        .HasForeignKey("ExecutedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany("Executions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutedByUser");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportField", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDataSource", "DataSource")
                        .WithMany("Fields")
                        .HasForeignKey("ReportDataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportFilter", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany("Filters")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportRelationship", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDataSource", "FromDataSource")
                        .WithMany()
                        .HasForeignKey("FromDataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany("Relationships")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.ReportDataSource", "ToDataSource")
                        .WithMany()
                        .HasForeignKey("ToDataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromDataSource");

                    b.Navigation("Report");

                    b.Navigation("ToDataSource");
                });

            modelBuilder.Entity("CadenceAccounting.Models.TimeEntry", b =>
                {
                    b.HasOne("CadenceAccounting.Models.Project", "Project")
                        .WithMany("TimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Company", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Project", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Invoices");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDataSource", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDefinition", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("DataSources");

                    b.Navigation("Executions");

                    b.Navigation("Filters");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("CadenceAccounting.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Expenses");

                    b.Navigation("Invoices");

                    b.Navigation("Projects");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
