// <auto-generated />
using System;
using CadenceAccounting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadenceAccounting.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027155600_AddCanvasDataToReportDefinition")]
    partial class AddCanvasDataToReportDefinition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadenceAccounting.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TableName", "RecordId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7441147f-9dea-4278-847e-a2560f66b044"),
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5199),
                            Email = "info@cadence-consulting.com",
                            Name = "Cadence Consulting LLC",
                            Phone = "(312) 555-0123",
                            TaxId = "12-3456789",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5200)
                        });
                });

            modelBuilder.Entity("CadenceAccounting.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInvoiced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiptFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("ReceiptImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("CadenceAccounting.Models.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("BankTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("ClientAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ContractDocument")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContractText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectNumber");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ProjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommonExpenses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("DefaultBudget")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("DefaultHourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DefaultTaxType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("ProjectTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8d423e1-ba59-4430-9af2-f1404e47cc36"),
                            CommonExpenses = "[\"Travel\", \"Meals\", \"Supplies\", \"Equipment\", \"Software\"]",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(6207),
                            DefaultBudget = 50000.00m,
                            DefaultHourlyRate = 75.00m,
                            DefaultTaxType = "1099",
                            Description = "Template for state government contracts",
                            Name = "State Contract",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(6215)
                        });
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataBinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("ZIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComponentType");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportComponents");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("SourceName");

                    b.ToTable("ReportDataSources");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedUserGroups")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanvasData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("bit");

                    b.Property<string>("PrintDateUDF")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReportGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsActive");

                    b.HasIndex("ReportGroup");

                    b.HasIndex("Title");

                    b.ToTable("ReportDefinitions");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExecutedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExecutionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ExecutionTimeMs")
                        .HasColumnType("int");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedBy");

                    b.HasIndex("ExecutionDate");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportExecutions");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FormatString")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsGroupBy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSortBy")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReportDataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SortDirection")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldName");

                    b.HasIndex("ReportDataSourceId");

                    b.ToTable("ReportFields");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FilterValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LogicOperator")
                        .HasColumnType("int");

                    b.Property<int>("Operator")
                        .HasColumnType("int");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ColumnName");

                    b.HasIndex("ReportId");

                    b.HasIndex("TableName");

                    b.ToTable("ReportFilters");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayField")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ParameterType")
                        .HasColumnType("int");

                    b.Property<string>("Prompt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ValueField")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterName");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportParameters");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportParameterOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId");

                    b.ToTable("ReportParameterOptions");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("FromDataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JoinType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToDataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FromDataSourceId");

                    b.HasIndex("ReportId");

                    b.HasIndex("ToDataSourceId");

                    b.ToTable("ReportRelationships");
                });

            modelBuilder.Entity("CadenceAccounting.Models.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c772e47-19ac-4e64-84ab-f13ffaaa346b"),
                            Category = "Invoice",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5351),
                            Description = "Invoice number format template",
                            Key = "InvoiceNumberFormat",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5352),
                            Value = "INV-{ProjectNumber}-{Year}-{SequentialNumber}"
                        },
                        new
                        {
                            Id = new Guid("9cdb87da-d691-43fa-ae29-23c42fb2ea3f"),
                            Category = "Tax",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5379),
                            Description = "Default tax type for new projects",
                            Key = "DefaultTaxType",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5380),
                            Value = "1099"
                        },
                        new
                        {
                            Id = new Guid("119246c6-6a3a-45f0-93f0-b6f48dfc6756"),
                            Category = "Tax",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5419),
                            Description = "Federal income tax withholding rate",
                            Key = "FederalWithholdingRate",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5420),
                            Value = "15.0"
                        },
                        new
                        {
                            Id = new Guid("4920be27-84e6-4691-8d30-0514eb316ad0"),
                            Category = "Tax",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5427),
                            Description = "Illinois state tax rate",
                            Key = "IllinoisStateTaxRate",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5428),
                            Value = "4.95"
                        },
                        new
                        {
                            Id = new Guid("afb4e13b-fae3-4c78-82d8-5001dd3c6070"),
                            Category = "Tax",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5781),
                            Description = "Social Security tax rate",
                            Key = "SocialSecurityRate",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5782),
                            Value = "6.2"
                        },
                        new
                        {
                            Id = new Guid("849fc624-d124-4c7e-979e-12e2ab2b81e9"),
                            Category = "Tax",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5785),
                            Description = "Medicare tax rate",
                            Key = "MedicareRate",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5786),
                            Value = "1.45"
                        },
                        new
                        {
                            Id = new Guid("92c09f99-ca2b-4654-b9b3-9d28f879272f"),
                            Category = "Project",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5797),
                            Description = "Default hourly rate for projects",
                            Key = "DefaultHourlyRate",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5798),
                            Value = "75.00"
                        },
                        new
                        {
                            Id = new Guid("2719264e-8eea-4013-b345-c747081ba222"),
                            Category = "Company",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5801),
                            Description = "Company name for invoices",
                            Key = "CompanyName",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5801),
                            Value = "Cadence Consulting LLC"
                        },
                        new
                        {
                            Id = new Guid("7a6377ce-7bf0-4ba3-bbf3-022cc2ff5fcc"),
                            Category = "Company",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5810),
                            Description = "Company email for invoices",
                            Key = "CompanyEmail",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5811),
                            Value = "info@cadence-consulting.com"
                        },
                        new
                        {
                            Id = new Guid("3be9e849-8733-49a5-8637-6329a6e8aeeb"),
                            Category = "Email",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5814),
                            Description = "SMTP server for email",
                            Key = "SMTP_Server",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5814),
                            Value = "smtp.office365.com"
                        },
                        new
                        {
                            Id = new Guid("dc7670b5-79d6-43df-ba08-094282bc951c"),
                            Category = "Email",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5822),
                            Description = "SMTP port for email",
                            Key = "SMTP_Port",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5891),
                            Value = "587"
                        },
                        new
                        {
                            Id = new Guid("3abf1001-13f4-4b8c-b240-1726c491149b"),
                            Category = "Backup",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5895),
                            Description = "Backup frequency",
                            Key = "Backup_Frequency",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5895),
                            Value = "Daily"
                        },
                        new
                        {
                            Id = new Guid("e474a56e-3b21-4a82-8a53-33807174c1c2"),
                            Category = "Backup",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5904),
                            Description = "Backup location",
                            Key = "Backup_Location",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5905),
                            Value = "C:\\Backups\\CadenceAccounting"
                        },
                        new
                        {
                            Id = new Guid("0d859be8-7122-482f-9134-c844d0f52369"),
                            Category = "UI",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5926),
                            Description = "Default theme",
                            Key = "Theme",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5927),
                            Value = "Journal"
                        },
                        new
                        {
                            Id = new Guid("da3bbd78-5f50-4874-a7e8-6f397d83208f"),
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5934),
                            Description = "Session timeout in minutes",
                            Key = "SessionTimeout",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(5935),
                            Value = "30"
                        });
                });

            modelBuilder.Entity("CadenceAccounting.Models.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInvoiced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("CadenceAccounting.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(2114),
                            Email = "admin@cadence-consulting.com",
                            EmailVerified = true,
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$/k6hHg7HTI4uq.q/k0jNzuf6ommYP1ScSaCk63yrpqmuZIIy3bDhK",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 10, 27, 15, 55, 59, 407, DateTimeKind.Utc).AddTicks(2140),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CadenceAccounting.Models.AuditLog", b =>
                {
                    b.HasOne("CadenceAccounting.Models.User", "ChangedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Expense", b =>
                {
                    b.HasOne("CadenceAccounting.Models.Project", "Project")
                        .WithMany("Expenses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Invoice", b =>
                {
                    b.HasOne("CadenceAccounting.Models.User", "CreatedByUser")
                        .WithMany("Invoices")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.Project", "Project")
                        .WithMany("Invoices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CadenceAccounting.Models.InvoiceItem", b =>
                {
                    b.HasOne("CadenceAccounting.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Payment", b =>
                {
                    b.HasOne("CadenceAccounting.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Project", b =>
                {
                    b.HasOne("CadenceAccounting.Models.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.User", "CreatedByUser")
                        .WithMany("Projects")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportComponent", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany("Components")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDataSource", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany("DataSources")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDefinition", b =>
                {
                    b.HasOne("CadenceAccounting.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportExecution", b =>
                {
                    b.HasOne("CadenceAccounting.Models.User", "ExecutedByUser")
                        .WithMany()
                        .HasForeignKey("ExecutedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany("Executions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutedByUser");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportField", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDataSource", "DataSource")
                        .WithMany("Fields")
                        .HasForeignKey("ReportDataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportFilter", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany("Filters")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportParameter", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportParameterOption", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportParameter", "Parameter")
                        .WithMany("Options")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportRelationship", b =>
                {
                    b.HasOne("CadenceAccounting.Models.ReportDataSource", "FromDataSource")
                        .WithMany()
                        .HasForeignKey("FromDataSourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.ReportDefinition", "Report")
                        .WithMany("Relationships")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.ReportDataSource", "ToDataSource")
                        .WithMany()
                        .HasForeignKey("ToDataSourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromDataSource");

                    b.Navigation("Report");

                    b.Navigation("ToDataSource");
                });

            modelBuilder.Entity("CadenceAccounting.Models.TimeEntry", b =>
                {
                    b.HasOne("CadenceAccounting.Models.Project", "Project")
                        .WithMany("TimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadenceAccounting.Models.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Company", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CadenceAccounting.Models.Project", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Invoices");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDataSource", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportDefinition", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("DataSources");

                    b.Navigation("Executions");

                    b.Navigation("Filters");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("CadenceAccounting.Models.ReportParameter", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("CadenceAccounting.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Expenses");

                    b.Navigation("Invoices");

                    b.Navigation("Projects");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
