using CadenceAccounting.Models;
using System.Text;

namespace CadenceAccounting.Services
{
    public class ReportHtmlGenerator
    {
        public async Task<string> GenerateHtmlAsync(ReportDefinition report, ReportData data)
        {
            var html = new StringBuilder();
            
            // Start HTML document
            html.AppendLine("<!DOCTYPE html>");
            html.AppendLine("<html lang=\"en\">");
            html.AppendLine("<head>");
            html.AppendLine("    <meta charset=\"UTF-8\">");
            html.AppendLine("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
            html.AppendLine("    <title>").Append(EscapeHtml(report.Title)).AppendLine("</title>");
            html.AppendLine("    <style>");
            html.AppendLine(GetCssStyles());
            html.AppendLine("    </style>");
            html.AppendLine("</head>");
            html.AppendLine("<body>");
            
            // Report header
            html.AppendLine("    <div class=\"report-header\">");
            html.AppendLine("        <h1 class=\"report-title\">").Append(EscapeHtml(report.Title)).AppendLine("</h1>");
            
            if (!string.IsNullOrEmpty(report.Description))
            {
                html.AppendLine("        <p class=\"report-description\">").Append(EscapeHtml(report.Description)).AppendLine("</p>");
            }
            
            html.AppendLine("        <div class=\"report-meta\">");
            html.AppendLine("            <span class=\"generation-date\">Generated: ").Append(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")).AppendLine("</span>");
            html.AppendLine("            <span class=\"execution-time\">Execution Time: ").Append(data.ExecutionTime.TotalMilliseconds.ToString("F0")).AppendLine(" ms</span>");
            html.AppendLine("        </div>");
            html.AppendLine("    </div>");
            
            // Report content
            html.AppendLine("    <div class=\"report-content\">");
            
            if (data.Rows.Any())
            {
                await AddDataTableAsync(html, data);
            }
            else
            {
                html.AppendLine("        <div class=\"no-data\">");
                html.AppendLine("            <p>No data available for the selected criteria.</p>");
                html.AppendLine("        </div>");
            }
            
            html.AppendLine("    </div>");
            
            // Report footer
            html.AppendLine("    <div class=\"report-footer\">");
            html.AppendLine("        <p>Report generated by Cadence Accounting System</p>");
            html.AppendLine("    </div>");
            
            html.AppendLine("</body>");
            html.AppendLine("</html>");
            
            return html.ToString();
        }

        private async Task AddDataTableAsync(StringBuilder html, ReportData data)
        {
            html.AppendLine("        <div class=\"data-table-container\">");
            html.AppendLine("            <table class=\"data-table\">");
            
            // Table header
            html.AppendLine("                <thead>");
            html.AppendLine("                    <tr>");
            foreach (var column in data.Columns)
            {
                html.Append("                        <th>").Append(EscapeHtml(column.Name)).AppendLine("</th>");
            }
            html.AppendLine("                    </tr>");
            html.AppendLine("                </thead>");
            
            // Table body
            html.AppendLine("                <tbody>");
            foreach (var row in data.Rows)
            {
                html.AppendLine("                    <tr>");
                foreach (var column in data.Columns)
                {
                    var value = row.ContainsKey(column.Name) ? row[column.Name] : "";
                    var displayValue = FormatCellValue(value);
                    html.Append("                        <td>").Append(EscapeHtml(displayValue)).AppendLine("</td>");
                }
                html.AppendLine("                    </tr>");
            }
            html.AppendLine("                </tbody>");
            html.AppendLine("            </table>");
            
            // Row count summary
            if (data.TotalRows > 0)
            {
                html.AppendLine("            <div class=\"table-summary\">");
                html.AppendLine("                <p>Total Rows: ").Append(data.TotalRows.ToString("N0")).AppendLine("</p>");
                html.AppendLine("            </div>");
            }
            
            html.AppendLine("        </div>");
        }

        private string FormatCellValue(object? value)
        {
            if (value == null || value == DBNull.Value)
                return "";
            
            if (value is DateTime dateTime)
                return dateTime.ToString("yyyy-MM-dd HH:mm:ss");
            
            if (value is decimal || value is double || value is float)
                return string.Format("{0:N2}", value);
            
            return value.ToString() ?? "";
        }

        private string EscapeHtml(string? text)
        {
            if (string.IsNullOrEmpty(text))
                return "";
            
            return text
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;")
                .Replace("'", "&#39;");
        }

        private string GetCssStyles()
        {
            return @"
                body {
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    margin: 0;
                    padding: 20px;
                    background-color: #f8f9fa;
                    color: #333;
                }
                
                .report-header {
                    background: white;
                    padding: 30px;
                    border-radius: 8px;
                    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                    margin-bottom: 20px;
                }
                
                .report-title {
                    margin: 0 0 10px 0;
                    color: #2c3e50;
                    font-size: 28px;
                    font-weight: 600;
                }
                
                .report-description {
                    margin: 0 0 15px 0;
                    color: #7f8c8d;
                    font-size: 16px;
                }
                
                .report-meta {
                    display: flex;
                    gap: 20px;
                    font-size: 12px;
                    color: #95a5a6;
                }
                
                .report-content {
                    background: white;
                    border-radius: 8px;
                    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                    overflow: hidden;
                }
                
                .data-table-container {
                    overflow-x: auto;
                }
                
                .data-table {
                    width: 100%;
                    border-collapse: collapse;
                    font-size: 14px;
                }
                
                .data-table th {
                    background-color: #34495e;
                    color: white;
                    padding: 12px 8px;
                    text-align: left;
                    font-weight: 600;
                    border-bottom: 2px solid #2c3e50;
                }
                
                .data-table td {
                    padding: 10px 8px;
                    border-bottom: 1px solid #ecf0f1;
                }
                
                .data-table tbody tr:nth-child(even) {
                    background-color: #f8f9fa;
                }
                
                .data-table tbody tr:hover {
                    background-color: #e8f4f8;
                }
                
                .table-summary {
                    padding: 15px 20px;
                    background-color: #f8f9fa;
                    border-top: 1px solid #ecf0f1;
                    font-size: 12px;
                    color: #7f8c8d;
                }
                
                .no-data {
                    padding: 40px;
                    text-align: center;
                    color: #7f8c8d;
                }
                
                .report-footer {
                    margin-top: 20px;
                    padding: 15px;
                    text-align: center;
                    font-size: 12px;
                    color: #95a5a6;
                }
                
                @media print {
                    body {
                        background: white;
                        padding: 0;
                    }
                    
                    .report-header,
                    .report-content {
                        box-shadow: none;
                        border: 1px solid #ddd;
                    }
                }
            ";
        }
    }
}
